apiVersion: apps/v1
kind: Deployment
metadata:
  app: nodejsapp
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nodejsapp

  template: 
    metadata:
      labels:
        app: nodejsapp
